name: 🥚 Bug Report
description: Something is not working as expected
title: "[Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
          Before opening new issue, make sure there are no existing requests by searching the [repository issues](https://github.com/Software-Noob/pterodactyl-images/issues?q=is%3Aissue+label%3Abug+).
    validations:
      required: true
  - type: textarea
    id: bug-report
    attributes:
      description: Explain the bug with as much information as possible including any error messages. Low effort bug reports will be closed.
      placeholder: Server crashed after doing X and Y. Error message is ... and previous console output is ...
    validations:
      required: true
