name: Build game images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - games/**

permissions:
  actions: read
  packages: write

concurrency:
  group: games-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "games_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - source-sourcemod

    steps:
      - name: Call reusable build image workflow
        uses: ./.github/workflows/build-docker-image.yml
        with:
          context: ./games
          platforms: linux/amd64
          file: ./games/${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/software-noob/pterodactyl-images:games_${{ matrix.tag }}
