name: build Java Dragonwell images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-dragonwell/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-dragonwell-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_dragonwell"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21

    steps:
      - name: Call reusable build image workflow
        uses: ./.github/workflows/build-docker-image.yml
        with:
          context: ./java-dragonwell
          platforms: linux/amd64, linux/arm64
          file: ./java-dragonwell/${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/software-noob/pterodactyl-images:java_${{ matrix.tag }}_dragonwell
