name: build java_openj9
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-openj9/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-openj9-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_openj9"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 16
          - 17
          - 18
          - 20
          - 21
    steps:
      - name: Call reusable build image workflow
        uses: ./.github/workflows/build-docker-image.yml
        with:
          context: ./java-openj9
          platforms: linux/amd64
          file: ./java-openj9/${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/software-noob/pterodactyl-images:java_${{ matrix.tag }}_openj9
