name: Build Java Shenandoah images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-shenandoah/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-shenandoah-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_shenandoah"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
    steps:
      - name: Call reusable build image workflow
        uses: ./.github/workflows/build-docker-image.yml
        with:
          context: ./java-shenandoah
          platforms: linux/amd64,linux/arm64
          dockerfile: ./java-shenandoah/${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/software-noob/pterodactyl-images:java_${{ matrix.tag }}_shenandoah
