name: Build Nodejs images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - nodejs/**

permissions:
  actions: read
  packages: write

concurrency:
  group: nodejs-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22

    steps:
      - name: Call reusable build image workflow
        uses: ./.github/workflows/build-docker-image.yml
        with:
          context: ./nodejs
          platforms: linux/amd64,linux/arm64
          dockerfile: ./nodejs/${{ matrix.tag }}/Dockerfile
          tags: ghcr.io/software-noob/pterodactyl-images:nodejs_${{ matrix.tag }}
